### PR TITLE
Updated the expired slack link

### PR DESCRIPTION
**Pull request by janithlahirukariyawasam**
### Please provide a brief explanation for this change:

The purpose of this PR is to update the expired slack link.
Replaced the expired slack link with the new one in the engineering-team.md file.
The goal is to provide new developers to join with the SEF community using the Slack platform without any issue.

**Screenshots**
----

src

After the Update
errorfix2

**Preview Link**
----
https://pr-16-sef-handbook.surge.sh/

### Please indicate the types of revisions being suggested for the Handbook (please check all that apply):

* [ ] Small improvement (typos, clarifications, etc.)
* [ ] Adding a new section
* [x] Modifying existing section
* [ ] Documenting a new process
* [ ] Adding a new page or directory
* [ ] Other

### Author Checklist

* [x] Provided a concise title for the PR
* [x] Provided a brief explanation for this change (Say why not just what)
  * (Attach screenshots, Slack conversations, etc. as necessary)
* [x] Indicated the types of changes included in this PR
* [x] Verified that no confidential data is in this PR

### CODE REVIEW

**Review by anjula-sack — APPROVED** [review]
Thank you! @janithlahirukariyawasam

**Comment by anjula-sack** [comment]
@janithlahirukariyawasam can you update this according to the pull request template? With preview link.

**Comment by janithlahirukariyawasam** [comment]
@anjula-sack Please can you help me to find the preview link?

**Comment by anjula-sack** [comment]
> @anjula-sack Please can you help me to find the preview link?

You can change your PR description based on this https://github.com/sef-global/sef-handbook/blob/main/.github/PULL_REQUEST_TEMPLATE.md. This has the preview link

**Comment by janithlahirukariyawasam** [comment]
@anjula-sack Can you check now?

**Comment by jayasanka-sack** [comment]
Can we join our slack workspace without an invitation link?

**Comment by jayasanka-sack** [comment]
Seems it isn't possible. 
@janithlahirukariyawasam the new link isn't expiring, right? 

If it is, I generated a non-expiry link for you: https://join.slack.com/t/sefheadquarters/shared_invite/zt-1h5zt3go4-wnRDDpecbWiTdpDv1VUoVg

**Comment by janithlahirukariyawasam** [comment]
@jayasanka-sack Well, Anjula provided this link to me,
 https://join.slack.com/t/sefheadquarters/shared_invite/zt-1jwub1lpd-RXYAMG46qXRUhOGZ7u_ewg   
So I replaced it with the expired link. I think it is ok? Do I need to change it with your link?





**This is the ERROR**
If you have a slack account already you don't face any issue by opening the link by clicking **workplace.**
Screenshot 2022-11-14 220424

But if you are a new developer who is going to join with slack first time you will get this error **This link is no longer active
To join this workspace, you’ll need to ask the person who originally invited you for a new link.**
Screenshot 2022-11-14 214644
You can check it by opening the workplace in private window in your broswer

**Comment by jayasanka-sack** [comment]
Thanks for getting this done @janithlahirukariyawasam ! 😍

**Pull request merged**
