### PR TITLE
Add new "Team Responsibilities" page

### LINKED ISSUE #21: Add new "Team Responsibilities" page
**Is your feature request related to a problem? Please describe.**
There is no page in the handbook which documents the responsibilities of a team member

**Describe the solution you'd like**
Create a subsection under the "Engineering Team" page, titled "Team Responsibilities", which should contain the content of this newly created [google doc](https://docs.google.com/document/d/1jRCIfa6SMzSPEh-NwxPySYLpu_Ra1co_r6LzBepa1C4/edit)

**Are you working on it?**
No

### PR DESCRIPTION
**Pull request by YoshithaRathnayake**
### Purpose:
The purpose of this PR is to fix #21 

### Related to:
Engineering team page

### Please provide a brief explanation for this change:

This PR adds a new section called "Team Responsibilities" to the engineering team page

**Preview Link:**

https://pr-22-sef-handbook.surge.sh/

### Please indicate the types of revisions being suggested for the Handbook (please check all that apply):

* [ ] Small improvement (typos, clarifications, etc.)
* [x] Adding a new section
* [ ] Modifying existing section
* [ ] Documenting a new process
* [ ] Adding a new page or directory
* [ ] Other

### Author Checklist

* [x] Provided a concise title for the PR
* [x] Provided a brief explanation for this change (Say why not just what)
  * (Attach screenshots, Slack conversations, etc. as necessary)
* [x] Indicated the types of changes included in this PR
* [x] Verified that no confidential data is in this PR
* [ ] Posted an update in [#handbook](https://sefheadquarters.slack.com/archives/C0376JVK2HF) channel
* [ ] If the changes affect team members, or warrant an announcement in another way, please consider posting an update in [#general](https://sefheadquarters.slack.com/archives/CJ89Y7JAV) channel

### CODE REVIEW

**Comment by YoshithaRathnayake** [comment]
@anjula-sack @miniskynet Can you review this changes?

**Comment by miniskynet** [comment]
Hi @YoshithaRathnayake. We want the new content in a new subsection page like this. The page should fall under the engineering team page: 
image

**Comment by YoshithaRathnayake** [comment]
> Hi @YoshithaRathnayake. We want the new content in a new subsection page like this. The page should fall under the engineering team page: image

Ok, can you tell me that file, which I should edit. @miniskynet

**Comment by miniskynet** [comment]
@YoshithaRathnayake You see that the dropdown of Handbook section has 3 subsections? Just like that create a subsection called Team Responsibilities for the Engineering Team section. Go through the category.json files, you'll get a better understanding on how sectioning works. You need to create a new md file for this.

**Comment by YoshithaRathnayake** [comment]
> @YoshithaRathnayake You see that the dropdown of Handbook section has 3 subsections? Just like that create a subsection called Team Responsibilities for the Engineering Team section. Go through the category.json files, you'll get a better understanding on how sectioning works. You need to create a new md file for this.

Ok I'll try

**Comment by miniskynet** [comment]
> > @YoshithaRathnayake You see that the dropdown of Handbook section has 3 subsections? Just like that create a subsection called Team Responsibilities for the Engineering Team section. Go through the category.json files, you'll get a better understanding on how sectioning works. You need to create a new md file for this.
> 
> Ok I'll try

Please refer to this [PR](https://github.com/sef-global/sef-handbook/pull/7) if you want a better understanding

**Comment by YoshithaRathnayake** [comment]
> > > @YoshithaRathnayake You see that the dropdown of Handbook section has 3 subsections? Just like that create a subsection called Team Responsibilities for the Engineering Team section. Go through the category.json files, you'll get a better understanding on how sectioning works. You need to create a new md file for this.
> > 
> > 
> > Ok I'll try
> 
> Please refer to this [PR](https://github.com/sef-global/sef-handbook/pull/7) if you want a better understanding

Thanks @miniskynet

**Comment by YoshithaRathnayake** [comment]
@miniskynet so I should create a dropdown like subsection with the name Engineering Team, then I should insert this team responsibilities page to that subsection, then where should I put the engineering team page, should I insert it to the engineering team subsection? Because can't add a page to the subsection

**Comment by miniskynet** [comment]
> @miniskynet so I should create a dropdown like subsection with the name Engineering Team, then I should insert this team responsibilities page to that subsection, then where should I put the engineering team page, should I insert it to the engineering team subsection? Because can't add a page to the subsection

Keep Engineering Team page as it is. The Team Responsibilities should be a new page which falls under the Engineering Team page.

**Comment by YoshithaRathnayake** [comment]
> > @miniskynet so I should create a dropdown like subsection with the name Engineering Team, then I should insert this team responsibilities page to that subsection, then where should I put the engineering team page, should I insert it to the engineering team subsection? Because can't add a page to the subsection
> 
> Keep Engineering Team page as it is. The Team Responsibilities should be a new page which falls under the Engineering Team page.

Not in a dropdown right? Just a new page? @miniskynet

**Comment by miniskynet** [comment]
> > > @miniskynet so I should create a dropdown like subsection with the name Engineering Team, then I should insert this team responsibilities page to that subsection, then where should I put the engineering team page, should I insert it to the engineering team subsection? Because can't add a page to the subsection
> > 
> > 
> > Keep Engineering Team page as it is. The Team Responsibilities should be a new page which falls under the Engineering Team page.
> 
> Not in a dropdown right? Just a new page? @miniskynet



> > > @miniskynet so I should create a dropdown like subsection with the name Engineering Team, then I should insert this team responsibilities page to that subsection, then where should I put the engineering team page, should I insert it to the engineering team subsection? Because can't add a page to the subsection
> > 
> > 
> > Keep Engineering Team page as it is. The Team Responsibilities should be a new page which falls under the Engineering Team page.
> 
> Not in a dropdown right? Just a new page? @miniskynet

A new page in a dropdown like this:

image

**Comment by YoshithaRathnayake** [comment]
> > > > @miniskynet so I should create a dropdown like subsection with the name Engineering Team, then I should insert this team responsibilities page to that subsection, then where should I put the engineering team page, should I insert it to the engineering team subsection? Because can't add a page to the subsection
> > > 
> > > 
> > > Keep Engineering Team page as it is. The Team Responsibilities should be a new page which falls under the Engineering Team page.
> > 
> > 
> > Not in a dropdown right? Just a new page? @miniskynet
> 
> > > > @miniskynet so I should create a dropdown like subsection with the name Engineering Team, then I should insert this team responsibilities page to that subsection, then where should I put the engineering team page, should I insert it to the engineering team subsection? Because can't add a page to the subsection
> > > 
> > > 
> > > Keep Engineering Team page as it is. The Team Responsibilities should be a new page which falls under the Engineering Team page.
> > 
> > 
> > Not in a dropdown right? Just a new page? @miniskynet
> 
> A new page in a dropdown like this:
> 
> image

So we can't create a dropdown in a current working page right? It should be blank (no page, only a link) @miniskynet

**Comment by miniskynet** [comment]
> > > > > @miniskynet so I should create a dropdown like subsection with the name Engineering Team, then I should insert this team responsibilities page to that subsection, then where should I put the engineering team page, should I insert it to the engineering team subsection? Because can't add a page to the subsection
> > > > 
> > > > 
> > > > Keep Engineering Team page as it is. The Team Responsibilities should be a new page which falls under the Engineering Team page.
> > > 
> > > 
> > > Not in a dropdown right? Just a new page? @miniskynet
> > 
> > 
> > > > > @miniskynet so I should create a dropdown like subsection with the name Engineering Team, then I should insert this team responsibilities page to that subsection, then where should I put the engineering team page, should I insert it to the engineering team subsection? Because can't add a page to the subsection
> > > > 
> > > > 
> > > > Keep Engineering Team page as it is. The Team Responsibilities should be a new page which falls under the Engineering Team page.
> > > 
> > > 
> > > Not in a dropdown right? Just a new page? @miniskynet
> > 
> > 
> > A new page in a dropdown like this:
> > image
> 
> So we can't create a dropdown in a current working page right? It should be blank (no page, only a link) @miniskynet

I think you are a bit confused. Let's have a call. Please reach out to me on slack :)

**Comment by YoshithaRathnayake** [comment]
Yes, I am. Ok I'll

**Comment by YoshithaRathnayake** [comment]
image

In my way the one and only solution is this @miniskynet

**Comment by YoshithaRathnayake** [comment]
I'll close this PR and open a new one

**Pull request closed without merging**
