### PR TITLE
Remove organization drop down

### LINKED ISSUE #27: Remove the organization drop down
**Is your feature request related to a problem? Please describe.**
The organization drop down covers all the other menu items

**Describe the solution you'd like**
I'd like to remove the 'Organization' drop down and keep of the elements outside

**Are you working on it?**
Yes

### PR DESCRIPTION
**Pull request by dave-v0**
To suggest a change to the [Handbook](https://handbook.sefglobal.org/), please review the [Handbook Guidlines](https://handbook.sefglobal.org/organisation/handbook/usage#handbook-guidelines) section.

### Purpose:
The purpose of this PR is to fix #27

### Please provide a brief explanation for this change:

The organisation drop down was removed and other links were deployed outside

**Preview Link:**

https://pr-29-sef-handbook.surge.sh/

### Please indicate the types of revisions being suggested for the Handbook (please check all that apply):

* [x] Small improvement (typos, clarifications, etc.)
* [x] Adding a new section
* [x] Modifying existing section
* [x] Documenting a new process
* [x] Adding a new page or directory
* [x] Other

### Author Checklist

* [x] Provided a concise title for the PR
* [x] Provided a brief explanation for this change (Say why not just what)
  * (Attach screenshots, Slack conversations, etc. as necessary)
* [x] Indicated the types of changes included in this PR
* [x] Verified that no confidential data is in this PR
* [x] Posted an update in [#handbook](https://sefheadquarters.slack.com/archives/C0376JVK2HF) channel
* [x] If the changes affect team members, or warrant an announcement in another way, please consider posting an update in [#general](https://sefheadquarters.slack.com/archives/CJ89Y7JAV) channel

### CODE REVIEW

**Comment by dave-v0** [comment]
Hey @anjula-sack can you take a look please?

**Review by YoshithaRathnayake — CHANGES_REQUESTED** [review]
@anjula-sack Will it look better if the introduction goes first?
@DilinaBandara 

image

**Comment by dave-v0** [comment]
@YoshithaRathnayake You mean 'introdcution' above 'about-sef'?
What do you think @anjula-sack ?

**Comment by YoshithaRathnayake** [comment]
> @YoshithaRathnayake You mean 'introdcution' above 'about-sef'? What do you think @anjula-sack ?

Yeah, but later I thought it's About SEF that means whole sef and the introduction is only a intro of handbook. That's why I hide that comment. @DilinaBandara

**Review by anjula-sack — APPROVED** [review]
Good job! @DilinaBandara

**Pull request merged**
