### PR TITLE
Add new "Team Responsibilities" page

### LINKED ISSUE #21: Add new "Team Responsibilities" page
**Is your feature request related to a problem? Please describe.**
There is no page in the handbook which documents the responsibilities of a team member

**Describe the solution you'd like**
Create a subsection under the "Engineering Team" page, titled "Team Responsibilities", which should contain the content of this newly created [google doc](https://docs.google.com/document/d/1jRCIfa6SMzSPEh-NwxPySYLpu_Ra1co_r6LzBepa1C4/edit)

**Are you working on it?**
No

### PR DESCRIPTION
**Pull request by YoshithaRathnayake**
### Purpose:
The purpose of this PR is to fix #21 

### Related to:
Engineering team page

### Please provide a brief explanation for this change:

This PR adds a new section called "Team Responsibilities" to the engineering team page

**Screenshots:**

image

**Preview Link:**

https://pr-23-sef-handbook.surge.sh/organisation/engineering-team/team-responsibilities

### Please indicate the types of revisions being suggested for the Handbook (please check all that apply):

* [ ] Small improvement (typos, clarifications, etc.)
* [x] Adding a new section
* [ ] Modifying existing section
* [ ] Documenting a new process
* [ ] Adding a new page or directory
* [ ] Other

### Author Checklist

* [x] Provided a concise title for the PR
* [x] Provided a brief explanation for this change (Say why not just what)
  * (Attach screenshots, Slack conversations, etc. as necessary)
* [x] Indicated the types of changes included in this PR
* [x] Verified that no confidential data is in this PR
* [ ] Posted an update in [#handbook](https://sefheadquarters.slack.com/archives/C0376JVK2HF) channel
* [ ] If the changes affect team members, or warrant an announcement in another way, please consider posting an update in [#general](https://sefheadquarters.slack.com/archives/CJ89Y7JAV) channel

### CODE REVIEW

**Comment by YoshithaRathnayake** [comment]
@anjula-sack @miniskynet can you solve this workflow error?

**Comment by miniskynet** [comment]
Hi @YoshithaRathnayake can you please change the name of the page from "Team" to "Being part of the Engineering Team"

**Comment by YoshithaRathnayake** [comment]
Can you check now? @miniskynet

**Comment by miniskynet** [comment]
Looks good @YoshithaRathnayake. Can you also change the title of the page to the same name? Currently it's engineering team. Also please update the screenshot with the new changes

**Comment by YoshithaRathnayake** [comment]
Now it's ok no? @miniskynet

**Review by anjula-sack — APPROVED** [review]
Good job! @YoshithaRathnayake

**Comment by miniskynet** [comment]
Thank you! @YoshithaRathnayake

**Pull request merged**
